sudo: required

dist: trusty

services:
  - docker

language: go

go:
  - 1.7

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

install:
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 21ff6d397ccca910873d8eaabab6a941c364cc70 && go install && cd -

script:
  - make test
