version: "2.0"

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:5.0.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile-fluentd
    ports:
      - 24224:24224
